coverage:
  precision: 2
  round: down
  range: 70...100

  status:
    project:
      default:
        target: 80%
        threshold: 1%

    patch:
      default:
        target: 80%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

ignore:
  - "cmd/tool-hub-mcp/main.go"  # Entry point
  - "scripts/*"                  # Build scripts
  - "npm/*"                      # NPM wrapper
